micronaut.application.name=driveflix

# ===== DATASOURCE =====
datasources.default.driverClassName=org.postgresql.Driver
datasources.default.url=${DATASOURCES_DEFAULT_URL:jdbc:postgresql://pg-2c5bca59-driveflix.d.aivencloud.com:12668/defaultdb?sslmode=require}
# jdbc:postgresql://db:5432/appdb link para db docker
datasources.default.username=${POSTGRES_USER:avnadmin}
datasources.default.password=${POSTGRES_PASSWORD:AVNS_9lSBDz3jXFQYFgz9yrE}


# ===== JPA / HIBERNATE =====
jpa.default.properties.hibernate.hbm2ddl.auto=update
jpa.default.properties.hibernate.show_sql=true
jpa.default.properties.hibernate.format_sql=true
jpa.default.entity-scan.packages=example.micronaut


# ===== CORS =====
micronaut.server.cors.enabled=true
micronaut.server.cors.configurations.web.allowed-origins[0]=http://localhost:5173
micronaut.server.cors.configurations.web.allowed-methods[0]=GET
micronaut.server.cors.configurations.web.allowed-methods[1]=POST
micronaut.server.cors.configurations.web.allowed-methods[2]=PUT
micronaut.server.cors.configurations.web.allowed-methods[3]=DELETE
micronaut.server.cors.configurations.web.allowed-methods[4]=OPTIONS

micronaut.server.host=0.0.0.0
micronaut.server.port=8080
