-- PostgreSQL database dump

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

DROP TABLE IF EXISTS public.clients CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;
DROP TABLE IF EXISTS public.pedidos CASCADE;
DROP TABLE IF EXISTS public.carros CASCADE;
DROP TABLE IF EXISTS public.agentes CASCADE;

-- ========================
-- Tabela users
-- ========================
CREATE TABLE public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) UNIQUE,
    password VARCHAR(255)
);

-- ========================
-- Tabela agentes
-- ========================
CREATE TABLE public.agentes (
    id BIGINT PRIMARY KEY,
    tipo VARCHAR(255),
    cnpj VARCHAR(255),
    razao_social VARCHAR(255),
    CONSTRAINT fk_agentes_user
        FOREIGN KEY (id)
        REFERENCES public.users(id)
        ON DELETE CASCADE
);

-- ========================
-- Tabela clients
-- ========================
CREATE TABLE public.clients (
    id BIGINT PRIMARY KEY,
    address VARCHAR(255),
    cpf VARCHAR(255),
    name VARCHAR(255),
    phone VARCHAR(255),
    rg VARCHAR(255),
    renda NUMERIC(15,2), -- ✅ ADICIONADO
    CONSTRAINT fk_clients_user
        FOREIGN KEY (id)
        REFERENCES public.users(id)
        ON DELETE CASCADE
);

-- ========================
-- Tabela carros
-- ========================
CREATE TABLE public.carros (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    marca VARCHAR(255),
    modelo VARCHAR(255),
    placa VARCHAR(255),
    status VARCHAR(255),
    preco DOUBLE PRECISION,
    imagem_url VARCHAR(255),
    agent_id BIGINT NOT NULL,
    CONSTRAINT fk_carros_agente
        FOREIGN KEY (agent_id)
        REFERENCES public.agentes(id)
);

-- ========================
-- Tabela pedidos
-- ========================
CREATE TABLE public.pedidos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_criacao TIMESTAMP WITHOUT TIME ZONE,
    status VARCHAR(255),
    parecer_financeiro VARCHAR(255),
    client_id BIGINT NOT NULL,
    car_id BIGINT NOT NULL,
    CONSTRAINT fk_pedidos_client
        FOREIGN KEY (client_id)
        REFERENCES public.clients(id),
    CONSTRAINT fk_pedidos_carro
        FOREIGN KEY (car_id)
        REFERENCES public.carros(id)
);

-- ========================
-- Inserts (mais seguros que COPY em dev)
-- ========================
INSERT INTO public.users (id, email, password) VALUES
(1, 'diogo@email.com', '123456'),
(2, 'teste@email.com', '123456'),
(3, 'digo@email.com', '123456');

INSERT INTO public.clients (id, address, cpf, name, phone, rg, renda) VALUES
(1, 'Rua A, 123', '12345678900', 'Diogo', '31999999999', '1234567', 2500.00),
(2, 'Rua B, 456', '32145678900', 'Test', '31989999999', '1134567', 8500.00),
(3, 'Rua A, 123', '12341678900', 'Diogo', '31999999999', '1234527', 3200.00);

-- ========================
-- Ajuste das sequences
-- ========================
SELECT setval('public.users_id_seq', (SELECT MAX(id) FROM public.users));